### PR TITLE
Added isometric renders of block models rendered in-game

### PR DESCRIPTION
**Pull request by gamma-02**
:D

### CODE REVIEW

**Comment by object-Object** [comment]
isn't the correct folder name `block`, not `blocks`?

**Comment by gamma-02** [comment]
Honestly, i have no clue: it _really_ varies through even Minecraft's code.......

**Comment by object-Object** [comment]
hex uses `block`: https://github.com/object-Object/HexMod/tree/docgen-2-1.20/Common/src/main/resources/assets/hexcasting/textures/block

**Comment by object-Object** [comment]
oh, also - could you perhaps generate a render for the Farmer's Delight skillet? I think it would be funny to show the true pansexual recipe

**Comment by gamma-02** [comment]
HAH

yeah, let me fix that

**Comment by gamma-02** [comment]
closing this, give me a miniute

**Pull request closed without merging**
